### PR TITLE
Avoided hardcoded values in RSS template

### LINKED ISSUE #1009: Avoid hardcoded values in RSS template. Take values like...
The puzzle `1004-e3426e23` from #1004 has to be resolved: 

https://github.com/fidals/shopelectro/blob/235fbccbc52e368038419262bc8f4ae895afea0c/templates/prices/price.rss#L7-L8

The puzzle was created by duker33 on 31-Oct-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by olegush**
Closes #1009

### CODE REVIEW

**Comment by duker33** [comment]
@olegush , append plz PR body with the related task in format `Closes #XXX`

**Comment by duker33** [comment]
@olegush , write the test just for title tag plz. To do it plz clone and customize that one `shopelectro.tests.tests_commands.PricesTest.test_items_in_price_rss`

**Comment by olegush** [comment]
Closes #1012

**Comment by olegush** [comment]
Closed by the reason:
```
+ git init
Initialized empty Git repository in /drone/shopelectro/.git/
+ git remote add origin https://github.com/fidals/shopelectro.git
+ git fetch --no-tags origin +refs/pull/1012/merge:
fatal: Couldn't find remote ref refs/pull/1012/merge
```

**Pull request closed without merging**
