### PR TITLE
#449  Reproduce volumes collision

### LINKED ISSUE #449: .drone.yml:33-36: Fix volumes collision for new drone...
The puzzle `352-3a47ae9f` from #352 has to be resolved:

https://github.com/fidals/shopelectro/blob/497ad6c4c65b6363fe6ee786a8b68be29d9e6783/.drone.yml#L33-L36

The puzzle was created by duker33 on 25-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by duker33**
Closes #449

### CODE REVIEW

**Comment by artemiy312** [comment]
@duker33 Let's not use `docker-compose` to build front's files. It will be simpler and easier

Instead of 
```yml
 npm:
   image: docker/compose
   commands:
     - ...
     - docker-compose run --rm nodejs gulp build
```

to do
```yml
  docker-build:
    image: docker/compose
    commands:
      ...
      - docker-compose -f docker-compose-build.yml build --no-cache nodejs python-dev
    ...

 pip-install:
    image: fidals/se:dev
    ...

 build-static:
   image: fidals/se-nodejs:dev
   commands:
     - gulp build # or `cp front_build /drone/front_build`
```

If we will decide to do so, then would be nice to update the created todos

**Comment by duker33** [comment]
@artemiy312 , it's great idea. The last moment is images sharing between containers, but seems i already met some recipe

**Comment by duker33** [comment]
@artemiy312 , idea has not so easy implementation.
I'll add this approach to todo task at `dc-volumes`, it's different task.

This PR closes #449. It contains research about volumes

**Comment by duker33** [comment]
@artemiy312 , appended it, review plz

**Pull request merged**
